name: Run Tests

on:
  push:
    branches:
     - main
     - develop
  pull_request:
    branches:
     - main
     - develop

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.17.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run Unit test
        run: bun run test
      - name: Run dev server and e2e tests
        run: |
          bun run dev &
          npx wait-on http://localhost:5173
          bun run test:e2e -- --no-runner-ui 
          kill $!
        env:
          NODE_ENV: development
          DATABASE_URL: "postgres://root:mysecretpassword@localhost:5432/local"